#!/bin/bash -l
#SBATCH --qos=regular
#SBATCH -N 4
#SBATCH -A m1820
#SBATCH -J music
#SBATCH -t 10:00:00
#SBATCH -L SCRATCH
#SBATCH -C knl,quad,cache

export OMP_PROC_BIND=spread
export OMP_PLACES=threads

num_of_nodes=4
# run all the job
for (( nodeid=1; nodeid <= $num_of_nodes; nodeid++ ))
do
    export OMP_NUM_THREADS=17
    srun -N 1 -n 16 -c 17 python job_MPI_wrapper.py 16 $nodeid &
done
wait
